//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS_01.TextResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HS_01.TextResource.RGlobal", typeof(RGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        public static string RAxtar {
            get {
                return ResourceManager.GetString("RAxtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloq.
        /// </summary>
        public static string RBloq {
            get {
                return ResourceManager.GetString("RBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış.
        /// </summary>
        public static string RÇıxış {
            get {
                return ResourceManager.GetString("RÇıxış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan Yerləşdir.
        /// </summary>
        public static string RElan_Yerləşdir {
            get {
                return ResourceManager.GetString("RElan Yerləşdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas Səhifə.
        /// </summary>
        public static string RƏsas_Səhifə {
            get {
                return ResourceManager.GetString("RƏsas Səhifə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat.
        /// </summary>
        public static string RQeydiyyat {
            get {
                return ResourceManager.GetString("RQeydiyyat", resourceCulture);
            }
        }
    }
}
