//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elanlar
    {
        public int ID { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AnimalId { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
